name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      GOLANGCI_LINT_VERSION: v2.13.2
      GOSEC_VERSION: v2.29.0
      CGO_ENABLED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols pkg-config

      - name: Cache golangci-lint cache
        uses: actions/cache@v6
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ hashFiles('**/.golangci.yml') }}
          restore-keys: |
            ${{ runner.os }}-golangci-lint-

      - name: Install dependencies
        run: go mod tidy

      - name: Run Go tests
        run: go test -v ./...

      - name: Run Gosec Security Scanner
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@${{ env.GOSEC_VERSION }}
          gosec ./...

      - name: Check code formatting
        run: |
          if ! gofmt -l . | grep .; then
            echo "All files are formatted correctly."
          else
            echo "Some files are not formatted. Please run 'gofmt -w .'"
            exit 1
          fi

      - name: Cache Go modules
        uses: actions/cache@v6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
